# Generated by Django 5.2.9 on 2025-12-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APagar",
            fields=[
                ("idcontapagar", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "valorparcela",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("numeroparcela", models.IntegerField(blank=True, null=True)),
                ("datavencimento", models.DateField(blank=True, null=True)),
                ("dataquitacao", models.DateField(blank=True, null=True)),
                (
                    "valordesconto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "valorjuros",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "db_table": "a_pagar",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AReceber",
            fields=[
                ("idconta", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "valorparcela",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("numeroparcela", models.IntegerField(blank=True, null=True)),
                ("datavencimento", models.DateField(blank=True, null=True)),
                ("dataquitacao", models.DateField(blank=True, null=True)),
                (
                    "valordesconto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "valorjuros",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "db_table": "a_receber",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, null=True, unique=True),
                ),
                ("logradouro", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bairro", models.CharField(blank=True, max_length=255, null=True)),
                ("cep", models.CharField(blank=True, max_length=9, null=True)),
                ("cidade", models.CharField(blank=True, max_length=255, null=True)),
                ("estado", models.CharField(blank=True, max_length=2, null=True)),
                ("tipousuario", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idcliente", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("cpf_cnpj", models.CharField(blank=True, max_length=14, null=True)),
                (
                    "rua",
                    models.CharField(
                        blank=True, db_column="logradouro", max_length=50, null=True
                    ),
                ),
                ("numero", models.IntegerField(blank=True, null=True)),
                ("complemento", models.CharField(blank=True, max_length=50, null=True)),
                ("bairro", models.CharField(blank=True, max_length=30, null=True)),
                ("cep", models.CharField(blank=True, max_length=8, null=True)),
                ("cidade", models.CharField(blank=True, max_length=50, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("estado", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "db_table": "clientes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.SmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Fornecedores",
            fields=[
                ("idfornecedor", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
                (
                    "cpf_cnpj",
                    models.CharField(blank=True, max_length=14, null=True, unique=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("logradouro", models.CharField(blank=True, max_length=50, null=True)),
                ("numero", models.IntegerField(blank=True, null=True)),
                ("complemento", models.CharField(blank=True, max_length=50, null=True)),
                ("bairro", models.CharField(blank=True, max_length=30, null=True)),
                ("cep", models.CharField(blank=True, max_length=8, null=True)),
                ("cidade", models.CharField(blank=True, max_length=30, null=True)),
                ("estado", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "db_table": "fornecedores",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlanoDeContas",
            fields=[
                ("idplanocontas", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(blank=True, max_length=30, null=True)),
                ("tipofluxocaixa", models.SmallIntegerField(blank=True, null=True)),
                ("conta", models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                "db_table": "plano_de_contas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Propriedades",
            fields=[
                ("idpropriedade", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(blank=True, max_length=30, null=True)),
                ("logradouro", models.CharField(blank=True, max_length=50, null=True)),
                ("numero", models.IntegerField(blank=True, null=True)),
                ("complemento", models.CharField(blank=True, max_length=50, null=True)),
                ("bairro", models.CharField(blank=True, max_length=30, null=True)),
                ("cep", models.CharField(blank=True, max_length=8, null=True)),
                ("cidade", models.CharField(blank=True, max_length=30, null=True)),
                ("estado", models.CharField(blank=True, max_length=2, null=True)),
                ("tipousuario", models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "propriedades",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UsuariosPropriedades",
            fields=[
                (
                    "idtiporelacaopropriedade",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "usuarios_propriedades",
                "managed": False,
            },
        ),
    ]
