# Generated by Django 5.2.9 on 2025-12-06 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("conta_atrasada", "Conta em atraso"),
                            ("conta_vencendo", "Conta vencendo"),
                            ("sistema", "Atualização do sistema"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                ("titulo", models.CharField(max_length=120, verbose_name="Título")),
                (
                    "subtitulo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subtítulo"
                    ),
                ),
                ("lida", models.BooleanField(default=False, verbose_name="Lida")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes_cadastros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-created_at"],
            },
        ),
    ]
