# Generated by Django 5.2.9 on 2025-12-06 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0002_notificacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoAgenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("inicio", models.DateTimeField(verbose_name="Início")),
                ("fim", models.DateTimeField(verbose_name="Fim")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("evento", "Evento"),
                            ("lembrete", "Lembrete"),
                            ("tarefa", "Tarefa"),
                            ("conta_pagar", "Conta a pagar"),
                            ("conta_receber", "Conta a receber"),
                        ],
                        default="evento",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "local",
                    models.CharField(blank=True, max_length=200, verbose_name="Local"),
                ),
                (
                    "participantes",
                    models.TextField(blank=True, verbose_name="Participantes"),
                ),
                (
                    "concluido",
                    models.BooleanField(default=False, verbose_name="Concluído"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "conta_pagar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_agenda",
                        to="cadastros.apagar",
                    ),
                ),
                (
                    "conta_receber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_agenda",
                        to="cadastros.areceber",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_agenda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de agenda",
                "verbose_name_plural": "Eventos de agenda",
            },
        ),
    ]
