# Generated by Django 5.2.9 on 2025-12-06 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0003_eventoagenda"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventoagenda",
            name="concluido",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="conta_pagar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastros.apagar",
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="conta_receber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastros.areceber",
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="fim",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="inicio",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="local",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="participantes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("evento", "Evento"),
                    ("lembrete", "Lembrete"),
                    ("tarefa", "Tarefa"),
                    ("conta_pagar", "Conta a pagar"),
                    ("conta_receber", "Conta a receber"),
                ],
                default="evento",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_agenda",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
