# Generated by Django 5.2.9 on 2025-12-05 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(max_length=11, unique=True, verbose_name="CPF"),
                ),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=10, verbose_name="Número"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Complemento"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=30, verbose_name="Bairro"),
                ),
                ("cep", models.CharField(blank=True, max_length=8, verbose_name="CEP")),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=30, verbose_name="Cidade"),
                ),
                (
                    "estado",
                    models.CharField(blank=True, max_length=2, verbose_name="Estado"),
                ),
                (
                    "tipousuario",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Admin"), (2, "Comum")],
                        default=2,
                        verbose_name="Tipo de usuário",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
