# Generated by Django 5.2.9 on 2025-12-06 02:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_notificacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificacao",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="notificacao",
            name="criada_em",
        ),
        migrations.AddField(
            model_name="notificacao",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Criada em",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="lida",
            field=models.BooleanField(default=False, verbose_name="Lida"),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="subtitulo",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Subtítulo"
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("conta_atrasada", "Conta a pagar em atraso"),
                    ("conta_vence_hoje", "Conta que vence hoje"),
                    ("atualizacao_sistema", "Atualização do sistema"),
                    ("outro", "Outro"),
                ],
                max_length=50,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="titulo",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificacoes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
